version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      tauri:
        patterns:
          - "tauri"
          - "tauri-build"
  - package-ecosystem: npm
    directory: "/src/tauri/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      unocss:
        patterns:
          - "@unocss/*"
          - "unocss"
      tauri:
        patterns:
          - "@tauri-apps/*"
