# Configuration for cargo-deny
# https://embarkstudios.github.io/cargo-deny/index.html
targets = [{ triple = "x86_64-pc-windows-msvc" }]
# When outputting inclusion graphs in diagnostics that include features, this
# option can be used to specify the depth at which feature edges will be added.
feature-depth = 1

[advisories]
unsound = "deny"
yanked = "deny"

[licenses]
copyleft = "deny"
allow-osi-fsf-free = "both"
# The confidence threshold for detecting a license from license text.
confidence-threshold = 0.8
allow = ["CC0-1.0", "MIT-0", "MPL-2.0", "Unicode-DFS-2016"]

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
