name: UI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "src/modlunky2/**"
      - "src/tests/**"
      - "requirements*.txt"

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./src/tauri

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup Rust caching
        uses: Swatinem/rust-cache@v2

      - run: npm install

      - run: npm run check

      - run: npm run build

      - name: Build Tauri
        uses: tauri-apps/tauri-action@v0
